export const initialContext = {
    dispatch: ()=>{},
    userselector: {},
    reposelector: {},
    username: '',
    setUsername: ()=>{},
    submit: false,
    setSubmit: ()=>{},
    repoCount: {current: 0},
    totalRepos: {current: 0},
    repoDetails: {
      hypered:false,
      description:'',
      forks_count:'',
      homepage:'',
      watchers_count:'',
      html_url:''
    },
    setMountInput: ()=>{},
    mountUserComp: false,
    setMountUserComp: ()=>{},
    input2: false,
    setInput2: ()=>{},
    timer: {current: 0},
    inc: {current: 0},
    loading: false,
    setLoading: ()=>{},
    errorDisplay: false,
    setErrorDisplay: ()=>{},
    repoBtnDisabled: true,
    setRepoBtnDisabled: ()=>{},
    repoBtnText: '',
    setRepoBtnText: ()=>{},
    apiEmpty: {current: false}
  }